#ifndef COMMON_DEFINES_H_INCLUDED
#define COMMON_DEFINES_H_INCLUDED

#define BOOST_ALL_DYN_LINK
#define BOOST_DISABLE_ASSERTS
#define BOOST_FILESYSTEM_NO_DEPRECATED
#define BOOST_SYSTEM_NO_DEPRECATED

#endif // COMMON_DEFINES_H_INCLUDED
